import React from 'react'
import differenceInCalendarDays from "@bit/date-fns.date-fns.difference-in-calendar-days";

const wordList =
[
    "tweet",
    "twain",
    "prime",
    "audio",
    "modem",
    "frame",
    "logic",
    "table",
    "intel",
    "quote",
    "codec",
    "arial",
    "debug",
    "force",
    "algol",
    "macro",
    "tower",
    "erase",
    "paint",
    "cache",
    "drive",
    "abort",
    "adobe",
    "popup",
    "pixel",
    "macro",
    "admin",
    "chmod",
    "unity",
    "input",
    "ezine",
    "block",
    "clock",
    "email",
    "stack",
    "trash",
    "field",
    "login",
    "bixby",
    "xhtml",
    "layer",
    "proxy",
    "phone",
    "cobol",
    "reset",
    "shell",
    "hertz",
    "multi",
    "track",
    "lsblk",
    "tilde",
    "cycle",
    "gamer",
    "basic",
    "title",
    "clean",
    "chown",
    "skill",
    "volts",
    "slice",
    "event",
    "print",
    "cname",
    "write",
    "learn",
    "linux",
    "targz",
    "howto",
    "enter",
    "alpha",
    "swift",
    "brick",
    "apple",
    "nginx",
    "patch",
    "mount",
    "power",
    "crash",
    "flash",
    "virus",
    "inbox",
    "limbo",
    "image",
    "speed",
    "react",
    "eprom",
    "block",
    "panel",
    "msata",
    "micro",
    "octal",
    "epoch",
    "robot",
    "logic",
    "close",
    "video",
    "ascii",
    "media",
    "mkdir",
    "forth",
    "touch",
    "array",
    "regex",
    "click",
    "purge",
    "excel",
    "spool",
    "addin",
    "queue",
    "forum",
    "start",
    "owner",
    "liion",
    "logon",
    "suite",
    "tools",
    "queue",
    "phish",
    "gates",
    "query",
    "morph",
    "stats",
    "addon",
    "cdrom",
    "laser",
    "cyber",
    "board",
    "mouse",
    "graph",
    "msdos",
    "coral",
    "pixel",
];

// calender days between
const differenceDays = differenceInCalendarDays(
  new Date(),
  new Date(2023, 1, 1, 0, 0),
) + 283;

// correct word person needs to guess
const correctWord = getCorrectWord();

// function to randomize the word
function getCorrectWord() {
  console.log(differenceDays)
  return wordList[differenceDays]
}

export {
    wordList,
    correctWord
}